name: 'PalmLoganalysis'
description: 'Provide summary and possible fixes for generated log files'

inputs:
  file_path:
    description: 'Path to log file'
    required: true
  api-key:
    description: 'PALM api key'
    required: true

runs:
  using: "composite"
  steps:
    - run: sudo chmod +x entrypoint.sh
      shell: bash
    - run: ./entrypoint.sh ${{ inputs.file_path }} ${{ inputs.api-key }} 
      shell: bash
      id: palm_analyzer
    - run: ls
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: report
        path: ./result.txt
