on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./
        with:
          api-key: ${{ secrets.API_KEY }}
          filename: log.lgo
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

